import QAndA from "@components/case-study/QandA";
import Container from "../Container";
export default function ServiceQandA() {
    const data = {
        title: "Your SEO services questions, answered.",
        QandA: [
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
            {
                question: 'How can I use an SEO case study to assess an agency?',
                answer: 'The best SEO case studies offer more than just numbers; they provide a narrative that gives you a glimpse into the agency’s approach to customer relationships and problem-solving. When reading them, consider how the agency discusses its collaboration with the customer. This can give you an idea of the agency’s communication style and commitment to customer success   A good case study should clearly outline what the customer’s objectives were and how the agency’s SEO strategy aimed to meet those goals.If the focus is solely on vanity metrics without tying back to the customer’s business objectives, it may be a red flag. \n Our case studies clearly illustrate our commitment to partnership and our singular focus on our customers’ success.',
            },
            {
                question: 'How do your SEO case studies illustrate your methodology?',
                answer: 'We designed our case studies to be transparent roadmaps of our unique approach to SEO. Each one starts with our customers’ specific challenge, from low organic traffic and poor keyword rankings to content that wasn’t driving conversions. \n We then delve into the tailored strategies we employed to tackle these issues. Whether it was on-page optimization, link building, or a comprehensive content overhaul, we detail the services and tactics that were part of the solution. \n But we don’t stop there. Our case studies also highlight the measurable outcomes of our efforts. We provide clear before-and-after metrics to show the impact of our actions on key performance indicators like organic traffic, conversion rates, and search engine rankings. \n In essence, our case studies serve as a comprehensive guide to our methodology, offering you a transparent look at our approach, execution, and the results we deliver.',
            },
        ]
    }
    return (
        <Container>
            <QAndA data={data} />
        </Container>
    )
}